---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
spec:
  replicas: {{ .Values.replica.nginx }}
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
      - name:  nginx
        image:  {{ .Values.image.nginx }}
        volumeMounts:
        - name: vol-cm-nginx-main
          mountPath: /usr/share/nginx/html
      volumes:
      - name: vol-cm-nginx-main
        configMap:
          name: cm-nginx-main
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: svc-nginx
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 80
    nodePort: 30072
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
